const CartTypes = {
  //CART
  CART_ADD_ITEM: 'CART_ADD_ITEM',
  CART_REMOVE_ITEM: 'CART_REMOVE_ITEM',
  CART_DECREASE_ITEM: 'CART_DECREASE_ITEM',
  CART_INCREASE_ITEM: 'CART_INCREASE_ITEM',
  CLEAR_CART: 'CLEAR_CART',
};

export default CartTypes;
