const ProductTypes = {
    FETCH_SUCCESS_PRODUCT_DETAILS: 'FETCH_SUCCESS_PRODUCT_DETAILS',
    FETCH_FAIL_PRODUCT_DETAILS: 'FETCH_FAIL_PRODUCT_DETAILS',
    FETCH_REQUEST_PRODUCT_DETAILS: 'FETCH_REQUEST_PRODUCT_DETAILS',
    FETCH_PRODUCT_REQUEST: 'FETCH_PRODUCT_REQUEST',
    FETCH_PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAIL: 'FETCH_PRODUCT_FAIL',
    SET_EDIT_PRODUCT_ID: 'SET_EDIT_PRODUCT_ID',
    SET_REMOVE_PRODUCT_ID: 'SET_REMOVE_PRODUCT_ID',
}

export default ProductTypes